STAC-8617: Include new tracer and centralize logic to build namespace…
StackVista/stackstate-process-agent pull request #63
Opened 2020-11-26 17:06 UTC by craffit

- Use new tracer
- Move logic for namespace generation based on loopback to this process agent
- Drop EndpointId etc from protobuf, it is not used in the protocol
- 'Deprecate' the scope field (it does not exist anymore in the agent, in sts it will be deprecated in another mr), namespaces are what is used now to determine where a connection lives

2020-11-27 12:38 UTC, craffit commented on checks/net_common.go
> +	if (isLoopback(connection.Local) || isLoopback(connection.Remote)) {
make this conjunction

2020-12-01 08:53 UTC, TizianoPerrucci requested changes

2020-12-01 08:53 UTC, TizianoPerrucci commented on Gopkg.lock
> +    "github.com/patrickmn/go-cache",
where does this new dependency come from ?

2020-12-01 08:53 UTC, TizianoPerrucci commented on checks/net_common.go
> +func formatNamespace(clusterName string, hostname string, connection common.ConnectionStats) string {
I feel we could improve this function which constructs the namespace. 
Right now is adding elements to a list, could we use a more strict system like a struct?
So if easy to add another fragment to the namespace in the future.

2020-12-01 11:22 UTC, craffit commented on Gopkg.lock
> +    "github.com/patrickmn/go-cache",
not sure.. after a go update

2020-12-01 12:24 UTC, TizianoPerrucci approved these changes
cool, thx

2020-12-01 15:20 UTC, merged